"""empty message

Revision ID: 6983058bf290
Revises: c4b9ccfbfe44
Create Date: 2025-02-02 13:42:32.027435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6983058bf290'
down_revision = 'c4b9ccfbfe44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_type_names', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_document_type_name', ['document_type_name'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_type_names', schema=None) as batch_op:
        batch_op.drop_constraint('uq_document_type_name', type_='unique')


    # ### end Alembic commands ###
