"""empty message

Revision ID: c4b9ccfbfe44
Revises: 6c282dd7dfa3
Create Date: 2025-02-02 12:21:06.974496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b9ccfbfe44'
down_revision = '6c282dd7dfa3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_applications_user', 'user', ['user'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_applications_user', type_='foreignkey')

    # ### end Alembic commands ###

